# Expressions

In [2]:
#1 + 2 * (3 * 4 * 5 / 6) ** 3 + 7 + 8 - 9 + 10

In [4]:
#1 + 2 * 3 * 4 * 5 / 6 ** 3 + 7 + 8 - 9 + 10

In [8]:
#4 * 5 / 6 ** 3

In [ ]:
#2 Names
#Names are given to values in Python using an assignment statement. In an assignment, a name is followed by = , which is followed by any expression.
#A name cannot contain a space; instead, it is common to use an underscore character _ to replace each space.

In [ ]:
Sales tax rate comprises of those levied by state, city and country. Given state_tax_rate = 0.075; county_tax_rate = 0.02
and city_tax_rate = 0.11, find the sales tax on a transaction of 1 lakh INR

In [2]:
purchase_price = 100000
state_tax_rate = 0.075
county_tax_rate = 0.02
city_tax_rate = 0.11
sales_tax_rate = state_tax_rate + county_tax_rate + city_tax_rate
sales_tax = purchase_price * sales_tax_rate
#sales_tax

In [ ]:
# Ex _Calculate Simple and Compound Interest given P = one lakh; rate of interest is 10% and years invested is 5

In [3]:
p = 100000
r = 0.10
n = 5
simple_interest = p*n*r
#simple_interest

In [15]:
#Comp_int
amount = p*(1+r)**n
#round(amount,2)

161051.0

In [25]:
#what would be the interest if the money has to multiply in 5 years?
rate_double = ((2**(1/5)) -1) * 100
#rate_double

14.869835499703509

In [ ]:
#================================End Arithmetic Operations=========Start Data Types======================

In [ ]:
Growth Rates
============
The relationship between two measurements of the same quantity taken at different times is
often expressed as a growth rate. 

For example, the US federal government employed 2,766,000 people in 2002 and 2,814,000 people in 2012. 
To compute a growth rate,  decide initial amount and the changed.

In [20]:
 initial = 2766000; final = 2814000

In [21]:
growth_rate = (final/initial) -1
round(growth_rate*100,2)

1.74

In [ ]:
""" In 10 years, the number of employees of the US Federal Government has increased as follows: initial = 2766K and changed = 2814K.
Find growth rate (ans: 1.74%)
In that time, the total expenditures of the US Federal Government increased from $2.37 trillion to $3.38 trillion in 2012. 
Compare the two (ans:42.6% increase in the federal budget is much larger than the 1.74% increase in federal employees).
Also compare with population growth of the United States, in the same time period (from 287.6 million people in 2002 
to 314.1 million in 2012 (ans: 9.21%)."""

In [97]:
# A useful property of growth rates is that they don't change even if the values are expressed in different units.
""" Can the groth rate be negative?- A growth rate can be negative, representing a decrease in some value. 
For example, the number of manufacturing jobs in the US decreased from 15.3 million in 2002 to 11.9 million
in 2012, a -22.2% growth rate."""

In [ ]:
""" An annual growth rate is a growth rate of some quantity over a single year. An annual growth
rate of 0.035, accumulated each year for 10 years, gives a much larger ten-year growth rate
of 0.41 (or 41%)."""

In [22]:
rate=( 1.035 * 1.035 * 1.035 * 1.035 * 1.035 * 1.035 * 1.035 * 1.035 *
1.035 * 1.035 - 1)

In [23]:
rate

0.410598760621121

In [24]:
#This same computation can be expressed using names and exponents
annual_growth_rate = 0.035
ten_year_growth_rate = (1 + annual_growth_rate) ** 10 - 1
ten_year_growth_rate

0.410598760621121

In [ ]:
""" Likewise, a ten-year growth rate can be used to compute an equivalent annual growth rate.
Below, t is the number of years that have passed between measurements. The following
computes the annual growth rate of federal expenditures over the last 10 years."""

In [25]:
initial = 2.37
changed = 3.38
t = 10
annual_growth_rate = (changed/initial) ** (1/t) - 1
annual_growth_rate

0.03613617208346853

In [ ]:
#The total growth over 10 years is equivalent to a 3.6% increase each year.

In [ ]:
""" In summary, a growth rate g is used to describe the relative size of an initial amount
and a changed amount after some amount of time t . To compute , apply the
growth rate g repeatedly, t times using exponentiation.
initial * (1 + g) ** t
To compute g , raise the total growth to the power of 1/t and subtract one.
(changed/initial) ** (1/t) - 1"""

In [ ]:
#Call Expressions

In [26]:
abs(-12)

12

In [27]:
max(2, 2 + 3, 4)

5

In [ ]:
In this last example, the max function is called on three arguments: 2, 5, and 4. The value
of each expression within parentheses is passed to the function, and the function returns the
final value of the full call expression. The max function can take any number of arguments
and returns the maximum.

In [28]:
""" A few functions are available by default, such as abs and round , but most functions that
are built into the Python language are stored in a collection of functions called a module. An
import statement is used to provide access to a module, such as math or operator ."""
import math
import operator
math.sqrt(operator.add(4, 5))

3.0

In [ ]:
""" Operators and call expressions can be used together in an expression. The percent
difference between two values is used to compare values for which neither one is obviously
initial or changed . 

Ex: In 2014 Florida farms produced 2.72 billion eggs while Iowa farms produced 16.25 billion eggs.
The percent difference is 100 times the absolute value of the difference between the values, divided by
their average. 
In this case, the difference is larger than the average, and so the percent difference is greater than 100."""

In [29]:
florida = 2.72
iowa = 16.25
100*abs(florida-iowa)/((florida+iowa)/2)

142.6462836056932

In [30]:
import math
import operator
math.sqrt(operator.add(4, 5))

3.0

In [31]:
#press tab key after dot and see
math.
math.log 

SyntaxError: invalid syntax (<ipython-input-31-3b27f970b879>, line 2)

In [ ]:
""" log(x[, base])
Return the logarithm of x to the given base.
If the base not specified, returns the natural logarithm (base e) of x."""

In [32]:
math.log(16, 2)

4.0

In [33]:
math.log(16)/math.log(2)

4.0

In [ ]:
*************************END - Programming Python - Part I******************************************

In [160]:
# Data types pp54
type(abs)

builtin_function_or_method

In [ ]:
""" When a float value is combined with an int value using some arithmetic operator, then
the result is always a float value. In most cases, two integers combine to form another
integer, but any number ( int or float ) divided by another will be a float value. Very
large or very small float values are displayed using scientific notation. """

In [34]:
.0000000000000000000000008709079

8.709079e-25

In [35]:
-12345678900000000000.0

-1.23456789e+19

In [ ]:
#Strings
""" From an existing string, related strings can be constructed using string methods, which are
functions that operate on strings. These methods are called by placing a dot after the string,
then calling the function.
--For example, the following method generates an uppercased version of a string loud"""

In [57]:
"loud".upper()

'LOUD'

In [58]:
'loud'.upper()

'LOUD'

In [ ]:
""" Perhaps the most important method is replace , which replaces all instances of a substring
within the string. The replace method takes two arguments, the text to be replaced and its
replacement. """

In [59]:
'hitchhiker'.replace('hi', 'ma')

'matchmaker'

In [60]:
s = "train"
t = s.replace('t', 'ing')
u = t.replace('in', 'de')
u

'degrade'

In [ ]:
""" Note that the line t = s.replace('t', 'ing') doesn't change the string s , which is still
"train". The method call s.replace('t', 'ing') just has a value, which is the string "ingrain". """

In [ ]:
Comparison -   Operator - True example - False Example
Less than          <           2 < 3       2 < 2
Greater than       >           3>2         3>3
Less than or equal <=          2 <= 2      3 <= 2
Greater or equal   >=          3 >= 3      2 >= 3
Equal              ==          3 == 3      3 == 2
Not equal          !=          3 != 2      2 != 2

In [164]:
#comparisons
3 > 1 + 1

True

In [62]:
"""Strings can also be compared, and their order is alphabetical. A shorter string is less than a
longer string that begins with the shorter string. """

"Dog" > "Catastrophe" > "Cat"

True

In [53]:
""" Single and double quotes can both be used to create strings: 'hi' and "hi" are identical
expressions. Double quotes are often preferred because they allow you to include
apostrophes inside of strings."""
"This won't work with a single-quoted string!"

"This won't work with a single-quoted string!"

In [55]:
#'This won't work with a single-quoted string!''

In [56]:
"""The str function returns a string representation of any value. Using this function, strings
can be constructed that have embedded values."""
"That's " + str(1 + 1) + ' ' + str(True)

"That's 2 True"

In [61]:
"""The average of two numbers is always between the smaller number and the larger number.
We express this relationship for the numbers x and y below. You can try different values
of x and y to confirm this relationship."""

x = 12
y = 5
min(x, y) <= (x+y)/2 <= max(x, y)

True

In [ ]:
#Sequences - Arrays

In [ ]:
""" Values can be grouped together into collections (array)  refer to all of them with a single name. 

--By grouping values together, write code that performs a computation on many pieces of data at once.

--Below, we collect four different temperatures into an array called highs, expressed as deviations from the
average absolute high temperature which was 14.48 degrees. """

In [37]:
import numpy as np

In [44]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
type(data2)

list

In [45]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2)
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [46]:
#array from lists
baseline_high = 14.48
highs = [baseline_high - 0.880, baseline_high - 0.093, baseline_high + 0.105, baseline_high + 0.684]
highs

[13.6, 14.387, 14.585, 15.164]

In [47]:
highs_array= np.array(highs)
highs_array

array([13.6  , 14.387, 14.585, 15.164])

In [48]:
#arrays from tuples
baseline_high = 14.48
highs = (baseline_high - 0.880, baseline_high - 0.093, baseline_high + 0.105, baseline_high + 0.684)
highs

(13.6, 14.387, 14.585, 15.164)

In [49]:
type(highs)

tuple

In [50]:
sum(highs)/len(highs)

14.434000000000001

In [51]:
highs_array = np.array(highs)
highs_array

array([13.6  , 14.387, 14.585, 15.164])

In [55]:
#another way to make an array...from strings
baseline_high = 14.48
highs = [baseline_high - 0.880, baseline_high - 0.093, baseline_high + 0.105, baseline_high + 0.684]
highs

[13.6, 14.387, 14.585, 15.164]

In [58]:
import numpy as np
highs_array = np.array(highs)
highs_array

array([13.6  , 14.387, 14.585, 15.164])

In [59]:
highs_array/len(highs)

array([3.4    , 3.59675, 3.64625, 3.791  ])

In [60]:
sum(highs)/len(highs)

14.434000000000001

In [61]:
# from tuples
english_parts_of_speech2 = ("noun", "pronoun", "verb","adverb", "adjective", "conjunction", "preposition","interjection")
english_parts_of_speech2_array = np.array(english_parts_of_speech2)

In [62]:
#Array from Strings
L = ["noun", "pronoun", "verb","adverb", "adjective", "conjunction", "preposition","interjection"]
english_parts_of_speech = np.array(L)
english_parts_of_speech

array(['noun', 'pronoun', 'verb', 'adverb', 'adjective', 'conjunction',
       'preposition', 'interjection'], dtype='<U12')

In [64]:
type(highs)

list

In [65]:
#convert to F
(9/5) * highs_array + 32

array([56.48  , 57.8966, 58.253 , 59.2952])

In [ ]:
""" Arrays also have methods, which are functions that operate on the array values. The mean
of a collection of numbers is its average value:"""

In [ ]:
""" Each pair of parentheses in the examples below is part of a call expression; it's calling a function with no
arguments to perform a computation on the array called highs . """

In [66]:
#Methods
highs_array
highs_array.size

4

In [67]:
highs_array.mean()

14.434000000000001

In [68]:
highs = highs_array
highs.sum()


57.736000000000004

In [70]:
# Numerical Python (NUMPY)- Functions on Arrays
#For example, the diff function computes the difference between each adjacent pair of
#elements in an array. The first element of the diff is the second element minus the first.
import numpy as np
np.diff(highs_array)

array([0.787, 0.198, 0.579])

In [ ]:
Function Description
np.prod- Multiply all elements together
np.sum -Add all elements together
np.all- Test whether all elements are true values (non-zero numbers are
true)
np.any- Test whether any elements are true values (non-zero numbers are
true)
np.count_nonzero- Count the number of non-zero elements

In [ ]:
Function Description
np.diff- Difference between adjacent elements
np.round- Round each number to the nearest integer (whole number)
np.cumprod- A cumulative product: for each element, multiply all elements so far
np.cumsum- A cumulative sum: for each element, add all elements so far
np.exp- Exponentiate each element
np.log- Take the natural logarithm of each element
np.sqrt- Take the square root of each element
np.sort- Sort the elements
Each of these functions takes an array of strings and returns an array.

In [ ]:
Function Description
np.char.lower- Lowercase each element
np.char.upper- Uppercase each element
np.char.strip- Remove spaces at the beginning or end of each element
np.char.isalpha- Whether each element is only letters (no numbers or symbols)
np.char.isnumeric- Whether each element is only numeric (no letters)
Each of these functions takes both an array of strings and a search string; each returns an array.

In [ ]:
Function Description
np.char.count- Count the number of times a search string appears among the
elements of an array
np.char.find- The position within each element that a search string is found
first
np.char.rfind- The position within each element that a search string is found
last
np.char.startswith- Whether each element starts with the search string

In [ ]:
#Range
"""A range is an array of numbers in increasing or decreasing order, each separated by a
regular interval. """

In [ ]:
Ranges are defined using the np.arange function, which takes either one, two, or three
arguments: a "start" - "end"-  "step".

---If you pass one argument to np.arange , this becomes the end value, with start=0 ,step=1 assumed. 
---Two arguments give the start and end with step=1 assumed. 
---Three arguments give the start , end and step explicitly.

A range always includes its start value, but does not include its end value. It counts up by step , and it stops before it gets to the end .
np.arange(end): An array starting with 0 of increasing consecutive integers, stopping before end.

In [71]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [72]:
np.arange(3, 9)

array([3, 4, 5, 6, 7, 8])

In [73]:
np.arange(3, 30, 5)

array([ 3,  8, 13, 18, 23, 28])

In [74]:
np.arange(1.5, -2, -0.5)

array([ 1.5,  1. ,  0.5,  0. , -0.5, -1. , -1.5])

In [75]:
baseline_low = 3.00
lows = (baseline_low - 0.872, baseline_low - 0.629,baseline_low - 0.126, baseline_low + 0.728)
lows

(2.128, 2.371, 2.874, 3.7279999999999998)

In [76]:
lows = np.array(lows)
lows

array([2.128, 2.371, 2.874, 3.728])

In [77]:
highs-lows

array([11.472, 12.016, 11.711, 11.436])

In [79]:
""" 
You may make use of make_array function from datascience library
from datascience.tables import *
from datascience.util import *
#compute the average daily range of temperatures #We could write this laboriously using .item :
make_array(highs.item(0) - lows.item(0),
           highs.item(1) - lows.item(1),
           highs.item(2) - lows.item(2),
           highs.item(3) - lows.item(3)
)""";

In [80]:
#Python provides a much cleaner way to write this:
highs - lows

array([11.472, 12.016, 11.711, 11.436])

In [42]:
#if array1 and array2 have the same number of elements, then the value of array1 * array2 is an array. 
#Its first element is the first element of array1 times the first element of array2 , 
#its second element is the second element of array1 times the second element of array2 , and so on.

In [ ]:
Refer Numpy - Leibniz & Wallis Calculation ppt (pp75)

In [81]:
#Lab3
#Leibniz formula for pi
positive_term_denominators = np.arange(1, 10000, 4)
positive_term_denominators

array([   1,    5,    9, ..., 9989, 9993, 9997])

In [24]:
positive_terms = 1 / positive_term_denominators
#The negative terms have 3, 7, 11, and so on on in their denominators. This array is just 2 added to positive_term_denominators .
negative_terms = 1 / (positive_term_denominators + 2)
#The overall sum is
4 * ( sum(positive_terms) - sum(negative_terms) )

3.1413926535917955

In [15]:
#Lab3
#Walli's Formula


In [25]:
even = np.arange(2, 1000001, 2)
one_below_even = even - 1
one_above_even = even + 1

In [26]:
2 * np.prod(even/one_below_even) * np.prod(even/one_above_even)

3.1415910827951143

In [ ]:
#=====================================================================================================================

In [109]:
##More Functions

In [82]:
def double(x):
    """ Double x """
    return 2*x

In [83]:
double(17)

34

In [84]:
any_name = 42
double(any_name)

84

In [85]:
arr = np.array([3, 4, 5])
arr

array([3, 4, 5])

In [86]:
def percent(x, total):
    """Convert x to a percentage of total.
    More precisely, this function divides x by total,
    multiplies the result by 100, and rounds the result
    to two decimal places.
    >>> percent(4, 16)
    25.0
    >>> percent(1, 6)
    16.67
    """
    return round((x/total)*100, 2)

In [87]:
def percents(counts):
    """Convert the values in array_x to percents out of the
    total of array_x."""
    total = counts.sum()
    return np.round((counts/total)*100, 2)

In [89]:
x = (7, 10, 4)
some_array = np.array(x)
percents(some_array)

array([33.33, 47.62, 19.05])

In [93]:
def biggest_difference(array_x):
    """Find the biggest difference in absolute value between two
    adjacent elements of array_x."""
    diffs = np.diff(array_x)
    absolute_diffs = abs(diffs)
    return max(absolute_diffs)

In [94]:
nums = (2, 4, 5, 6, 4, -1, 1)
some_numbers = np.array(nums)

In [ ]:
# OR

In [96]:
some_numbers = np.array([2, 4, 5, 6, 4, -1, 1])

In [97]:
big_diff = biggest_difference(some_numbers)
print("The biggest difference is", big_diff)

The biggest difference is 5


In [98]:
diffs = np.diff(some_numbers)

In [99]:
diffs

array([ 2,  1,  1, -2, -5,  2])

In [100]:
absolute_diffs = abs(diffs)

In [101]:
absolute_diffs

array([2, 1, 1, 2, 5, 2])

In [102]:
#Multiple Arguments


In [103]:
def percents(counts, decimal_places):
    """Convert the values in array_x to percents out of the
    total of array_x."""
    total = counts.sum()
    return np.round((counts/total)*100, decimal_places)
    

In [104]:
def percents(counts, decimal_places=2):
    """Convert the values in array_x to percents out of the
    total of array_x."""
    total = counts.sum()
    return np.round((counts/total)*100, decimal_places)

In [105]:
parts = np.array([2, 1, 4])

In [108]:
print("Rounded to 1 decimal place: ", percents(parts, 1))
print("Rounded to 2 decimal places:", percents(parts, 2))
print("Rounded to 3 decimal places:", percents(parts, 3))

Rounded to 1 decimal place:  [28.6 14.3 57.1]
Rounded to 2 decimal places: [28.57 14.29 57.14]
Rounded to 3 decimal places: [28.571 14.286 57.143]


In [109]:
print("Rounded to the default number of decimal places:",percents(parts))

Rounded to the default number of decimal places: [28.57 14.29 57.14]


In [110]:
#pp179 
#Applying a Function to a Column¶

In [112]:
def cut_off_at_100(x):
    """The smaller of x and 100"""
    return min(x, 100)
cut_off_at_100(17)

17

In [113]:
cut_off_at_100(117)

100

In [ ]:
# Matrix multiplication....We need install numpy in order to import it 

In [114]:
# input two matrices 
mat1 = ([1, 6, 5],[3 ,4, 8],[2, 12, 3]) 
mat2 = ([3, 4, 6],[5, 6, 7],[6,56, 7]) 

In [115]:
mat1

([1, 6, 5], [3, 4, 8], [2, 12, 3])

In [116]:
# This will return dot product 
result = np.dot(mat1,mat2) 
# print resulted matrix 
print(result) 


[[ 63 320  83]
 [ 77 484 102]
 [ 84 248 117]]


In [117]:
mat1 = ([1,2,3],[1,1,1])

In [118]:
mat1

([1, 2, 3], [1, 1, 1])

In [119]:
mat2 = ([1,1],[1,1], [1,1])  

In [120]:
result = np.dot(mat1,mat2)
result

array([[6, 6],
       [3, 3]])

In [121]:
sum(result)

array([9, 9])

In [123]:
np.cumsum(result)

array([ 6, 12, 15, 18], dtype=int32)