In [3]:
import numpy as np

In [1]:
abs(-3)

3

In [ ]:
"""Arrays
The central feature of NumPy is the array object class. Arrays are similar to lists in Python, except that every element of an array must be of the same type, typically a numeric type like float or int. Arrays make operations with large amounts of numeric data very fast and are generally much more efficient than lists.
An array can be created from a list:  """

In [5]:
a = np.array([1, 4, 5, 8], float)
a

array([1., 4., 5., 8.])

In [6]:
a = np.array([1, 4, 5, 8], int)
a

array([1, 4, 5, 8])

In [8]:
 type(a[2])

numpy.int32

In [9]:
a[:2]

array([1, 4])

In [ ]:
""" Arrays can be multidimensional. Unlike lists, different axes are accessed using commas inside bracket notation. 
Here is an example with a two-dimensional array (e.g., a matrix): """

In [10]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [ ]:
"""Array slicing works with multiple dimensions in the same way as usual, applying each slice specification as a filter to a specified dimension. 
Use of a single ":" in a dimension indicates the use of everything along that dimension: 

a[1,:] array([ 4., 5., 6.]) >>> a[:,2] array([ 3., 6.]) >>> a[-1:,-2:] array([[ 5., 6.]]) """

In [14]:
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.]])

In [15]:
a[:,2]

array([3., 6.])

In [12]:
a[1,:]

array([4., 5., 6.])

In [16]:
a[-1,:]

array([4., 5., 6.])

In [18]:
a[:,-2]

array([2., 5.])

In [20]:
a[:,:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [22]:
a[:1,:]

array([[1., 2., 3.]])

In [23]:
a[:2,:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [24]:
a[:2,:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
a = np.array([[1, 2, 3], [4, 5, 6], [7,8,9]], float)
a

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [26]:
a[:2,:]

array([[1., 2., 3.],
       [4., 5., 6.]])

In [27]:
a[:1,:]

array([[1., 2., 3.]])

In [28]:
a[:3,:]

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [29]:
a[:2,:1]

array([[1.],
       [4.]])

In [30]:
a[:2,:2]

array([[1., 2.],
       [4., 5.]])

In [31]:
a[:2,:-1]

array([[1., 2.],
       [4., 5.]])

In [32]:
a[:2,:-2]

array([[1.],
       [4.]])

In [33]:
a[-1:,-2:]

array([[8., 9.]])

In [34]:
a.shape

(3, 3)

In [35]:
a.dtype

dtype('float64')

In [ ]:
Here, float64 is a numeric type that NumPy uses to store double-precision (8-byte) real numbers, similar to the float type in Python.

In [37]:
len(a)

3

In [39]:
#When used with an array, the len function returns the length of the first axis:
""" The in statement can be used to test if values are present in an array:"""
2 in a 

True

In [41]:
0 in a

False

In [42]:
""" Arrays can be reshaped using tuples that specify new dimensions. In the following example, we turn a ten-element 
one-dimensional array into a two-dimensional one whose first axis has five elements and whose second axis has two elements:"""
a = np.array(range(10), float) 
a 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
a = a.reshape((5, 2))

In [44]:
a

array([[0., 1.],
       [2., 3.],
       [4., 5.],
       [6., 7.],
       [8., 9.]])

In [46]:
#Notice that the reshape function creates a new array and does not itself modify the original array.
a.shape

(5, 2)

In [ ]:
""" Keep in mind that Python's name-binding approach still applies to arrays. 
The copy function can be used to create a new, separate copy of an array in memory if needed:"""

In [49]:
a = np.array([1, 2, 3], float)
b = a
c = a.copy()   
a[0] = 0 

In [50]:
b

array([0., 2., 3.])

In [51]:
# Note no change in copy
c

array([1., 2., 3.])

In [ ]:
#Lists can also be created from arrays: 
a = np.array([1, 2, 3], float) 

In [53]:
a

array([0., 2., 3.])

In [54]:
a.tolist()

[0.0, 2.0, 3.0]

In [55]:
type(a.tolist())

list

In [56]:
type(a)

numpy.ndarray

In [59]:
#One can fill an array with a single value: 
a = np.array([1, 2, 3], float) 

In [60]:
a 

array([1., 2., 3.])

In [61]:
a.fill(0)
a

array([0., 0., 0.])

In [ ]:
""" Transposed versions of arrays can also be generated, which will create a new array with the final two axes switched:"""

In [64]:
a = np.array(range(6), float)
a

array([0., 1., 2., 3., 4., 5.])

In [69]:
b = a.reshape((2, 3)) 

In [ ]:
 a array([[ 0., 1., 2.], [ 3., 4., 5.]]) 

In [71]:
b.transpose() 

array([[0., 3.],
       [1., 4.],
       [2., 5.]])

In [72]:
#One-dimensional versions of multi-dimensional arrays can be generated with flatten: 
a = np.array([[1, 2, 3], [4, 5, 6]], float)
a 

array([[1., 2., 3.],
       [4., 5., 6.]])

In [73]:
a.flatten()

array([1., 2., 3., 4., 5., 6.])

In [74]:
"""Two or more arrays can be concatenated together using the concatenate function with a tuple of the arrays to be joined:"""
a = np.array([1,2], float) 
b = np.array([3,4,5,6], float) 
c = np.array([7,8,9], float)
np.concatenate((a, b, c)) 

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [75]:
""" If an array has more than one dimension, it is possible to specify the axis along which multiple arrays are concatenated. 
By default (without specifying the axis), NumPy concatenates along the first dimension: """
a = np.array([[1, 2], [3, 4]], float)
b = np.array([[5, 6], [7,8]], float) 
np.concatenate((a,b))  

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [76]:
np.concatenate((a,b), axis=0) 

array([[1., 2.],
       [3., 4.],
       [5., 6.],
       [7., 8.]])

In [77]:
np.concatenate((a,b), axis=1) 

array([[1., 2., 5., 6.],
       [3., 4., 7., 8.]])

In [ ]:
#Finally, the dimensionality of an array can be increased using the newaxis constant in bracket notation:
#Notice here that in each case the new array has two dimensions; the one created by newaxis has a length of one. 
#The newaxis approach is convenient for generating the proper-dimensioned arrays for vector and matrix mathematics.

In [78]:
a = np.array([1, 2, 3], float) 
a[:,np.newaxis] 

array([[1.],
       [2.],
       [3.]])

In [79]:
a[:,np.newaxis].shape 


(3, 1)

In [89]:
b

array([[5., 6.],
       [7., 8.]])

In [88]:
a[np.newaxis,:] 

array([[1., 2., 3.]])

In [84]:
b[np.newaxis,:].shape 

(1, 2, 2)

In [ ]:
""" Other ways to create arrays
The arange function is similar to the range function but returns an array: 
np.arange(5, dtype=float)  


In [90]:
np.arange(1, 6, 2, dtype=int)

array([1, 3, 5])

In [91]:
#The functions zeros and ones create new arrays of specified dimensions filled with these values. 
#These are perhaps the most commonly used functions to create new arrays: 
np.ones((2,3), dtype=float) 

array([[1., 1., 1.],
       [1., 1., 1.]])

In [92]:
np.zeros(7, dtype=int) 

array([0, 0, 0, 0, 0, 0, 0])

In [93]:
a = np.array([[1, 2, 3], [4, 5, 6]], float) 
np.zeros_like(a) 

array([[0., 0., 0.],
       [0., 0., 0.]])

In [94]:
np.ones_like(a)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [95]:
#There are also a number of functions for creating special matrices (2D arrays). 
#To create an identity matrix of a given size, 
np.identity(4, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [98]:
np.eye(4, k=1, dtype=float)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [99]:
np.eye(4, k=0, dtype=float)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [100]:
np.eye(4, k=2, dtype=float)

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
""" Array mathematics
When standard mathematical operations are used with arrays, they are applied on an element-by-element basis. 
This means that the arrays should be the same size during addition, subtraction, etc.:"""

In [101]:
a = np.array([1,2,3], float)

In [102]:
b = np.array([5,2,6], float)

In [103]:
a + b 

array([6., 4., 9.])

In [107]:
a - b

array([-4.,  0., -3.])

In [108]:
a * b

array([ 5.,  4., 18.])

In [109]:
b / a

array([5., 1., 2.])

In [110]:
a % b

array([1., 0., 3.])

In [111]:
b**a

array([  5.,   4., 216.])

In [ ]:
"""For two-dimensional arrays, multiplication remains elementwise and does not correspond to matrix multiplication. 
There are special functions for matrix math """

In [112]:
a = np.array([[1,2], [3,4]], float) 
b = np.array([[2,0], [1,3]], float) 
a * b 

array([[ 2.,  0.],
       [ 3., 12.]])

In [113]:
#Errors are thrown if arrays do not match in size: 
a = np.array([1,2,3], float) 
b = np.array([4,5], float) 
a + b Traceback (most recent call last)

SyntaxError: invalid syntax (<ipython-input-113-e7a00b9b1cca>, line 4)

In [ ]:
#ValueError: shape mismatch: objects cannot be broadcast to a single shape

In [ ]:
""" However, arrays that do not match in the number of dimensions will be broadcasted by Python to perform mathematical operations. 
This often means that the smaller array will be repeated as necessary to perform the operation indicated. Consider the following: """

In [114]:
a = np.array([[1, 2], [3, 4], [5, 6]], float) 
b = np.array([-1, 3], float) 
a + b

array([[0., 5.],
       [2., 7.],
       [4., 9.]])

In [ ]:
"""In addition to the standard operators, NumPy offers a large library of common mathematical functions that can be applied 
elementwise to arrays. Among these are the functions: abs, sign, sqrt, log, log10, exp, sin, cos, tan, arcsin, 
arccos, arctan, sinh, cosh, tanh, arcsinh, arccosh, and arctanh. """

In [3]:
import numpy as np
a = np.array([1, 4, 9], float)
a

array([1., 4., 9.])

In [4]:
np.sqrt(a)

array([1., 2., 3.])

In [ ]:
""" The functions floor, ceil, and rint give the lower, upper, or nearest (rounded) integer: >>> a = np.array([1.1, 1.5, 1.9], float) >>> np.floor(a) array([ 1., 1., 1.]) >>> np.ceil(a) array([ 2., 2., 2.]) 
>>> np.rint(a) array([ 1., 2., 2.])
Also included in the NumPy module are two important mathematical constants: >>> np.pi 3.1415926535897931 >>> np.e 2.7182818284590451

"""

In [ ]:
"""Array iteration
It is possible to iterate over arrays in a manner similar to that of lists:  ... <hit return> 1 4 5
For multidimensional arrays, iteration proceeds over the first axis such that each loop returns a subsection of the array: """

In [6]:
a = np.array([1, 4, 5], int) 
for x in a: 
    print(x)

1
4
5


In [7]:
a = np.array([[1, 2], [3, 4], [5, 6]], float) 
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [8]:
for x in a:
    print(x)

[1. 2.]
[3. 4.]
[5. 6.]


In [9]:
for (x, y) in a:
    print(x * y)

2.0
12.0
30.0


In [ ]:
""" Basic array operations
Many functions exist for extracting whole-array properties. The items in an array can be summed or multiplied: 

In this example, member functions of the arrays were used. Alternatively, standalone functions in the NumPy module can be accessed: >>> np.sum(a) 9.0 >>> np.prod(a) 24.0
For most of the routines described below, both standalone and member functions are available.
A number of routines enable computation of statistical quantities in array datasets, such as the mean (average), variance, and standard deviation: """

In [10]:
a = np.array([2, 4, 3], float) 
a.sum() 

9.0

In [11]:
a.prod() 

24.0

In [12]:
a = np.array([2, 1, 9], float) 
a.mean() 
a.var() 
a.std()

3.559026084010437

In [14]:
a.max()

9.0

In [15]:
a.min()

1.0

In [18]:
#The argmin and argmax functions return the array indices of the minimum and maximum values: 
a = np.array([2, 1, 9], float) 
a.argmin() 

1

In [ ]:
a.argmax()

In [17]:
"""For multidimensional arrays, each of the functions thus far described can take an optional argument axis that 
will perform an operation along only the specified axis, placing the results in a return array: 
Like lists, arrays can be sorted:"""

2

In [21]:
a = np.array([[0, 2], [3, -1], [3, 5]], float) 
a

array([[ 0.,  2.],
       [ 3., -1.],
       [ 3.,  5.]])

In [22]:
a.mean(axis=0)  

array([2., 2.])

In [23]:
a.mean(axis=1) 

array([1., 1., 4.])

In [24]:
a.min(axis=1)

array([ 0., -1.,  3.])

In [26]:
a.min(axis=0)

array([ 0., -1.])

In [27]:
a = np.array([6, 2, 5, -1, 0], float)
a

array([ 6.,  2.,  5., -1.,  0.])

In [28]:
sorted(a)

[-1.0, 0.0, 2.0, 5.0, 6.0]

In [30]:
a.sort()
a

array([-1.,  0.,  2.,  5.,  6.])

In [ ]:
#Values in an array can be "clipped" to be within a prespecified range. 
#This is the same as applying min(max(x, minval), maxval) to each element x in an array.

In [31]:
a = np.array([6, 2, 5, -1, 0], float) 
a.clip(0, 5)

array([5., 2., 5., 0., 0.])

In [32]:
#Unique elements can be extracted from an array: 
a = np.array([1, 1, 4, 5, 5, 5, 7], float) 
np.unique(a)

array([1., 4., 5., 7.])

In [33]:
#For two dimensional arrays, the diagonal can be extracted: 
a = np.array([[1, 2], [3, 4]], float) 
a.diagonal()

array([1., 4.])

In [ ]:
"""Comparison operators and value testing
Boolean comparisons can be used to compare members elementwise on arrays of equal size. 
The return value is an array of Boolean True / False values:"""

In [63]:
a = np.array([1, 3, 0], float) 
b = np.array([0, 3, 2], float) 
a > b

array([ True, False, False])

In [64]:
a == b 

array([False,  True, False])

In [65]:
a <= b

array([False,  True,  True])

In [ ]:
#The results of a Boolean comparison can be stored in an array: >>> c = a > b >>> c

In [66]:
c = a > b 
c

array([ True, False, False])

In [68]:
#To count the occurences of a value in a numpy array. 
print(np.sum(c==True))

1


In [38]:
#Arrays can be compared to single values using broadcasting: 
a = np.array([1, 3, 0], float) 
a > 2

array([False,  True, False])

In [39]:
#The any and all operators can be used to determine whether or not any or all elements of a Boolean array are true: 
c = np.array([ True, False, False], bool) 

In [40]:
any(c)

True

In [46]:
import collections, numpy
collections.Counter(c)

Counter({True: 1, False: 2})

In [49]:
c.count('True')

AttributeError: 'numpy.ndarray' object has no attribute 'count'

In [41]:
all(c)

False

In [44]:
import collections, numpy

a = numpy.array([0, 3, 0, 1, 0, 1, 2, 1, 0, 0, 0, 0, 1, 3, 4])
collections.Counter(a)

Counter({0: 7, 3: 2, 1: 4, 2: 1, 4: 1})

In [48]:
[1, 2, 3, 4, 1, 4, 1].count(1)

3

In [50]:
c = [1, 2, 3, 4, 1, 4, 1]

In [52]:
c.count(4)

2

In [60]:
import numpy as np
#To count the occurences of a value in a numpy array. 
import numpy as np
a=np.array([0,3,4,3,5,4,7])
print(np.sum(a==3))

2


In [ ]:
""" Vector and matrix mathematics
NumPy provides many functions for performing standard vector and matrix multiplication routines. 
The dot function also generalizes to matrix multiplication:"""

In [69]:
a = np.array([1, 2, 3], float)
b = np.array([0, 1, 1], float)
np.dot(a, b)

5.0

In [70]:
a = np.array([[0, 1], [2, 3]], float)
b = np.array([2, 3], float)
np.dot(b, a)

array([ 6., 11.])

In [71]:
np.dot(a, b)

array([ 3., 13.])

In [72]:
np.outer(a, b)

array([[0., 0.],
       [2., 3.],
       [4., 6.],
       [6., 9.]])

In [ ]:
"""NumPy also comes with a number of built-in routines for linear algebra calculations. 
These can be found in the sub-module linalg. Among these are routines for dealing with matrices and their inverses. 
The determinant of a matrix can be found:

In [73]:
a = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float) 
np.linalg.det(a)

-48.00000000000003

In [ ]:
#One can find the eigenvalues and eigenvectors of a matrix:

In [74]:
vals, vecs = np.linalg.eig(a)

In [75]:
vals

array([ 8.85591316,  1.9391628 , -2.79507597])

In [76]:
vecs

array([[-0.3663565 , -0.54736745,  0.25928158],
       [-0.88949768,  0.5640176 , -0.88091903],
       [-0.27308752,  0.61828231,  0.39592263]])

In [78]:
#The inverse of a matrix can be found: 
b = np.linalg.inv(a)
b

array([[ 0.22916667,  0.04166667, -0.29166667],
       [ 0.04166667, -0.08333333,  0.58333333],
       [-0.3125    ,  0.125     ,  0.125     ]])

In [79]:
#Singular value decomposition (analogous to diagonalization of a nonsquare matrix) can also be performed: 
a = np.array([[1, 3, 4], [5, 2, 3]], float)  
U, s, Vh = np.linalg.svd(a)

In [80]:
U

array([[-0.6113829 , -0.79133492],
       [-0.79133492,  0.6113829 ]])

In [81]:
s

array([7.46791327, 2.86884495])

In [82]:
Vh

array([[-0.61169129, -0.45753324, -0.64536587],
       [ 0.78971838, -0.40129005, -0.46401635],
       [-0.046676  , -0.79349205,  0.60678804]])

In [ ]:
#Polynomial mathematics
NumPy supplies methods for working with polynomials. Given a set of roots, it is possible to show the polynomial coefficients: 
Here, the return array gives the coefficients corresponding to .

In [84]:
np.poly([-1, 1, 1, 10])

array([  1., -11.,   9.,  11., -10.])

In [85]:
#The opposite operation can be performed: given a set of coefficients, the root function returns all of the polynomial roots: 
np.roots([1, 4, -2, 3])

array([-4.5797401 +0.j        ,  0.28987005+0.75566815j,
        0.28987005-0.75566815j])

In [86]:
np.roots([1,4,4]) # i.e. root of (x^2+4x+4)

array([-2., -2.])

In [87]:
np.poly([-2,-2]) # Reverse process, given roots -2 and -2, generate the poly (x^2+4x+4)

array([1., 4., 4.])

In [ ]:
#Coefficient arrays of polynomials can be integrated. Consider integrating (x^3+x^2+x+1) ⁄ ⁄ ⁄ . By default, the constant is set to zero:

In [88]:
np.polyint([1, 1, 1, 1]) # (o.25x^4+.....

array([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

In [89]:
#Similarly, derivatives can be taken: 
np.polyder([0.25      , 0.33333333, 0.5       , 1.        , 0.        ])

array([1.        , 0.99999999, 1.        , 1.        ])

In [ ]:
#The functions polyadd, polysub, polymul, and polydiv also handle proper addition, subtraction, multiplication, 
#and division of polynomial coefficients, respectively.The function polyval evaluates a polynomial at a particular point. 
#Consider evaluated at : ( x^3-2x^2+1 ) evaluate at x = 4

In [90]:
np.polyval([1, -2, 0, 2], 4)

34

In [ ]:
"""Statistics
In addition to the mean, var, and std functions, NumPy supplies several other methods for returning statistical features of arrays.
The median can be found: """  

In [91]:
a = np.array([1, 4, 3, 8, 9, 2, 3], float) 
np.median(a)

3.0

In [92]:
#correlation coefficient for multiple variables observed at multiple instances
a = np.array([[1, 2, 1, 3], [5, 3, 1, 8]], float) 
c = np.corrcoef(a) 
c

array([[1.        , 0.72870505],
       [0.72870505, 1.        ]])

In [ ]:
"""Random numbers
An important part of any simulation is the ability to draw random numbers. 
For this purpose, we use NumPy's built-in pseudorandom number generator routines in the sub-module random. 
The numbers are pseudo random in the sense that they are generated deterministically from a seed number, 
but are distributed in what has statistical similarities to random fashion. 
NumPy uses a particular algorithm called the Mersenne Twister to generate pseudorandom numbers.
The random number seed can be set: """

In [93]:
np.random.seed(293423)

In [ ]:
""" The seed is an integer value. Any program that starts with the same seed will generate exactly the same sequence of 
random numbers each time it is run. This can be useful for debugging purposes, but one does not need to specify the seed 
and in fact, when we perform multiple runs of the same simulation to be averaged together, we want each such trial to have
a different sequence of random numbers. If this command is not run, NumPy automatically selects a random seed (based on the time) 
that is different every time a program is run.
An array of random numbers in the half-open interval [0.0, 1.0) can be generated:

In [94]:
np.random.rand(5)

array([0.33677247, 0.52693437, 0.79529578, 0.78867702, 0.02147624])

In [95]:
#The rand function can be used to generate two-dimensional random arrays, or the resize function could be employed here: 
np.random.rand(2,3)

array([[0.84612516, 0.0704939 , 0.1526965 ],
       [0.77831701, 0.80821151, 0.82198398]])

In [96]:
np.random.rand(6).reshape((2,3))

array([[0.90239653, 0.8385685 , 0.02638565],
       [0.33681448, 0.46480928, 0.61686496]])

In [97]:
#To generate a single random number in [0.0, 1.0)
np.random.random()

0.43767262538051455

In [ ]:
#To generate random integers in the range [min, max) use randint(min, max): 

In [98]:
np.random.randint(5, 10)

5

In [99]:
np.random.randint(5, 10)

6

In [100]:
np.random.seed(293423)
np.random.randint(5, 10)

9

In [101]:
np.random.seed(293423)
np.random.randint(5, 10)

9

In [ ]:
"""In each of these examples, we drew random numbers form a uniform distribution. NumPy also includes generators 
for many other distributions, including the Beta, binomial, chi-square, Dirichlet, exponential, F, Gamma, geometric, 
Gumbel, hypergeometric, Laplace, logistic, log-normal, logarithmic, multinomial, multivariate, negative binomial, 
noncentral chi-square, noncentral F, normal, Pareto, Poisson, power, Rayleigh, Cauchy, student's t, triangular, von Mises,
Wald, Weibull, and Zipf distributions. Here we only give examples for two of these. """

In [102]:
#To draw from the discrete Poisson distribution with lambda = 6
np.random.poisson(6.0)

5

In [103]:
#To draw from a continuous normal (Gaussian) distribution with mean 1.5 and standard deviation 4:
np.random.normal(1.5, 4.0)

3.2067741436775075

In [104]:
#To draw from a standard normal distribution omit the arguments
np.random.normal()

-0.5324581382754698

In [105]:
#To draw multiple values, use the optional size argument:
np.random.normal(size=5)

array([ 0.48976147,  0.46881252,  2.27416107, -0.68480213, -1.16325047])

In [118]:
""" The random module can also be used to randomly shuffle the order of items in a list. 
This is sometimes useful if we want to sort a list in random order: """
a = np.arange(1,10) 
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
np.random.shuffle(a)
a

array([4, 5, 8, 2, 6, 3, 7, 1, 9])

In [123]:
arr = np.arange(10)
np.random.shuffle(arr)
arr

array([9, 8, 0, 2, 5, 3, 7, 1, 4, 6])

In [ ]:
#Notice that the shuffle function modifies the list in place, meaning it does not return a new list but rather modifies the original list itself

In [ ]:
#Modules available in SciPy
#SciPy greatly extends the functionality of the NumPy routines.. Many SciPy routines can be accessed by simply importing the module: 
#import scipy